***Pandas***

***Import Pandas library***

In [4]:
import pandas as pd

***load a csv file***

In [6]:
df = pd.read_csv("student-data.csv")

***quick exploration***

In [17]:
df #viewing dataframe

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [ ]:
print(df.head()) #first five datas

In [ ]:
print(df.tail()) #last five datas

In [8]:
print(df.shape) #rows and columns

(395, 31)

In [9]:
print(df.info()) #

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  passed      395 non-null    object
dtypes: int64(13), object(18)
memory usage: 95.8+ KB
None

In [10]:
print(df.describe()) #describes the data(counts no. of data,finds mean.... )

              age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000

         absences
count  395.000000
mean     5.708861
std      8.003096
min      0.000000
25%      0.000000
50%      4.000000
75%      8.000000
max     75.000000

In [15]:
print(pd.DataFrame(df))

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0    ...       no       no       4         3      4    1    1      3        6
1    ...      yes       no       5         3      3    1    1      3        4
2    ...      yes       no       4         3      2    2    3      3       10
3    ...      yes      yes       3         2      2    1    1      5        2
4    ...       no       no       4         3      2    1    2      5        4
..   ...      ...      ...     ...       ...    ...  ...  ...    ...      ...
390  ...       no       no       5         5      4    4    5      4       11
391  ...      yes       no       2         4      5    3    4      2        3
392  ...       no       no       5         5      3    3    3      3        3
393  ...      yes       no       4         4      1    3    4      5        0
394  ...      yes       no       3         2      3    3    3      5        5

    passed
0       no
1       no
2      yes
3      yes
4      yes
..     ...
390     no
391    yes
392     no
393    yes
394     no

[395 rows x 31 columns]

***Data selection***

In [24]:
df["school"] #specific column

0      GP
1      GP
2      GP
3      GP
4      GP
       ..
390    MS
391    MS
392    MS
393    MS
394    MS
Name: school, Length: 395, dtype: object

In [25]:
df["school"][390] #selection of data

'MS'

In [26]:
df["school"][390]='Arunima School' #changing the data
df["school"][390]

/tmp/ipykernel_920/1246760123.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["school"][390]='Arunima School' #changing the data

'Arunima School'

In [21]:
df.iloc[67:72] #row selection

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
67,GP,F,16,U,GT3,T,3,1,services,other,...,yes,no,4,3,3,1,2,5,4,no
68,GP,F,15,R,LE3,T,2,2,health,services,...,yes,no,4,1,3,1,3,4,2,no
69,GP,F,15,R,LE3,T,3,1,other,other,...,yes,no,4,4,2,2,3,3,12,yes
70,GP,M,16,U,GT3,T,3,1,other,other,...,yes,no,4,3,2,1,1,5,0,yes
71,GP,M,15,U,GT3,T,4,2,other,other,...,yes,no,3,3,3,1,1,3,0,yes

***Data filtering***

In [28]:
df[df['age']>18] #filters data on the basis of age

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
127,GP,F,19,U,GT3,T,0,1,at_home,other,...,no,no,3,4,2,1,1,5,2,no
153,GP,M,19,U,GT3,T,3,2,services,at_home,...,yes,yes,4,5,4,1,1,4,0,no
210,GP,F,19,U,GT3,T,3,3,other,other,...,yes,no,4,3,3,1,2,3,10,no
247,GP,M,22,U,GT3,T,3,1,services,services,...,yes,yes,5,4,5,5,5,1,16,no
257,GP,M,19,U,LE3,A,4,3,services,at_home,...,yes,no,4,3,1,1,1,1,12,yes
270,GP,F,19,U,GT3,T,3,3,other,services,...,yes,no,4,3,5,3,3,5,15,no
296,GP,F,19,U,GT3,T,4,4,health,other,...,yes,no,2,3,4,2,3,2,0,no
304,GP,M,19,U,GT3,T,3,3,other,other,...,yes,yes,4,4,4,1,1,3,20,yes
306,GP,M,20,U,GT3,A,3,2,services,other,...,no,no,5,5,3,1,1,5,0,yes
307,GP,M,19,U,GT3,T,4,4,teacher,services,...,yes,yes,4,3,4,1,1,4,38,no
308,GP,M,19,R,GT3,T,3,3,other,services,...,no,yes,4,5,3,1,2,5,0,yes
309,GP,F,19,U,LE3,T,1,1,at_home,other,...,yes,no,4,4,3,1,3,3,18,yes
310,GP,F,19,U,LE3,T,1,2,services,services,...,no,yes,4,2,4,2,2,3,0,no
311,GP,F,19,U,GT3,T,2,1,at_home,other,...,yes,yes,3,4,1,1,1,2,20,yes
312,GP,M,19,U,GT3,T,1,2,other,services,...,yes,no,4,5,2,2,2,4,3,yes
313,GP,F,19,U,LE3,T,3,2,services,other,...,yes,yes,4,2,2,1,2,1,22,yes
314,GP,F,19,U,GT3,T,1,1,at_home,health,...,yes,yes,4,1,2,1,1,3,14,yes
315,GP,F,19,R,GT3,T,2,3,other,other,...,yes,yes,4,1,2,1,1,3,40,yes
336,GP,F,19,R,GT3,A,3,1,services,at_home,...,no,no,5,4,3,1,2,5,12,yes
340,GP,F,19,U,GT3,T,2,1,services,services,...,yes,yes,4,3,4,1,3,3,4,yes
350,MS,M,19,R,GT3,T,1,1,other,services,...,yes,no,5,4,4,3,3,2,8,no
353,MS,M,19,R,GT3,T,1,1,other,other,...,yes,no,4,4,4,3,3,5,4,no
370,MS,F,19,U,LE3,T,3,2,services,services,...,no,yes,3,2,2,1,1,3,4,no
376,MS,F,20,U,GT3,T,4,2,health,other,...,yes,yes,5,4,3,1,1,3,4,yes
383,MS,M,19,R,GT3,T,1,1,other,services,...,no,no,4,3,2,1,3,5,0,no
387,MS,F,19,R,GT3,T,2,3,services,other,...,yes,no,5,4,2,1,2,5,0,no
390,Arunima School,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [31]:
#multiple conditions
#AND Condition
df[
    (df['sex'] == 'F')
    & (df['age'] > 18)
    & (df['age'] < 25)
]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
127,GP,F,19,U,GT3,T,0,1,at_home,other,...,no,no,3,4,2,1,1,5,2,no
210,GP,F,19,U,GT3,T,3,3,other,other,...,yes,no,4,3,3,1,2,3,10,no
270,GP,F,19,U,GT3,T,3,3,other,services,...,yes,no,4,3,5,3,3,5,15,no
296,GP,F,19,U,GT3,T,4,4,health,other,...,yes,no,2,3,4,2,3,2,0,no
309,GP,F,19,U,LE3,T,1,1,at_home,other,...,yes,no,4,4,3,1,3,3,18,yes
310,GP,F,19,U,LE3,T,1,2,services,services,...,no,yes,4,2,4,2,2,3,0,no
311,GP,F,19,U,GT3,T,2,1,at_home,other,...,yes,yes,3,4,1,1,1,2,20,yes
313,GP,F,19,U,LE3,T,3,2,services,other,...,yes,yes,4,2,2,1,2,1,22,yes
314,GP,F,19,U,GT3,T,1,1,at_home,health,...,yes,yes,4,1,2,1,1,3,14,yes
315,GP,F,19,R,GT3,T,2,3,other,other,...,yes,yes,4,1,2,1,1,3,40,yes
336,GP,F,19,R,GT3,A,3,1,services,at_home,...,no,no,5,4,3,1,2,5,12,yes
340,GP,F,19,U,GT3,T,2,1,services,services,...,yes,yes,4,3,4,1,3,3,4,yes
370,MS,F,19,U,LE3,T,3,2,services,services,...,no,yes,3,2,2,1,1,3,4,no
376,MS,F,20,U,GT3,T,4,2,health,other,...,yes,yes,5,4,3,1,1,3,4,yes
387,MS,F,19,R,GT3,T,2,3,services,other,...,yes,no,5,4,2,1,2,5,0,no

In [34]:
#OR condition
df[
    (df['sex'] == 'M')
    | (df['age'] > 18)
]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
5,GP,M,16,U,LE3,T,4,3,services,other,...,yes,no,5,4,2,1,2,5,10,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes
8,GP,M,15,U,LE3,A,3,2,services,other,...,yes,no,4,2,2,1,1,1,0,yes
9,GP,M,15,U,GT3,T,3,4,other,other,...,yes,no,5,5,1,1,1,5,0,yes
12,GP,M,15,U,LE3,T,4,4,health,services,...,yes,no,4,3,3,1,3,5,2,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,Arunima School,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

***Sorting***

In [41]:
#ascending
df.sort_values(by='absences')

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
23,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,5,4,4,2,4,5,0,yes
6,GP,M,16,U,LE3,T,2,2,other,other,...,yes,no,4,4,4,1,1,3,0,yes
33,GP,M,15,U,LE3,T,3,3,other,other,...,yes,no,5,3,2,1,1,2,0,yes
30,GP,M,15,U,GT3,T,4,4,health,services,...,yes,no,5,4,2,3,4,5,0,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,GP,M,19,U,GT3,T,4,4,teacher,services,...,yes,yes,4,3,4,1,1,4,38,no
315,GP,F,19,R,GT3,T,2,3,other,other,...,yes,yes,4,1,2,1,1,3,40,yes
74,GP,F,16,U,GT3,T,3,3,other,services,...,yes,no,4,3,3,2,4,5,54,yes
183,GP,F,17,U,LE3,T,3,3,other,other,...,yes,yes,5,3,3,2,3,1,56,no
276,GP,F,18,R,GT3,A,3,2,other,services,...,yes,yes,4,1,1,1,1,5,75,no

In [63]:
#desending
df.sort_values(by='absences',ascending=False)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,passed,performance,final-health
276,GP,F,18,R,GT3,A,3,2,other,services,...,4,1,1,1,1,5,75,no,5,10
183,GP,F,17,U,LE3,T,3,3,other,other,...,5,3,3,2,3,1,56,no,5,6
74,GP,F,16,U,GT3,T,3,3,other,services,...,4,3,3,2,4,5,54,yes,5,10
315,GP,F,19,R,GT3,T,2,3,other,other,...,4,1,2,1,1,3,40,yes,5,8
307,GP,M,19,U,GT3,T,4,4,teacher,services,...,4,3,4,1,1,4,38,no,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,GP,M,18,U,GT3,T,4,3,teacher,other,...,5,4,5,2,3,5,0,no,5,10
389,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,0,no,5,10
388,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,0,no,5,6
387,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,0,no,5,10
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,yes,5,10

***New COlumn***

In [59]:
df["performance"] = 5
df["final-health"]=(
    df["health"]+df["performance"]
)
print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences passed performance  \
0      4        3      4     1     1      3        6     no           5
1      5        3      3     1     1      3        4     no           5
2      4        3      2     2     3      3       10    yes           5
3      3        2      2     1     1      5        2    yes           5
4      4        3      2     1     2      5        4    yes           5

  final-health
0            8
1            8
2            8
3           10
4           10

[5 rows x 33 columns]

***cleaning Messy Data***
Missing values

In [49]:
df.isnull()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
391,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
393,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [51]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
passed        0
dtype: int64

In [60]:
#drop Missing rows
df.dropna(axis=1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,passed,performance,final-health
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,no,5,8
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,no,5,8
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,yes,5,8
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,yes,5,10
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,yes,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,Arunima School,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,no,5,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,yes,5,7
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,no,5,8
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,yes,5,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,no,5,10

***GroupBy***

In [68]:
#Average Marks By Class
df['address'] = df['address'].replace({'R': 'Kathmandu', 'U': 'Lalitpur'})
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,passed,performance,final-health
0,GP,F,18,Lalitpur,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,no,5,8
1,GP,F,17,Lalitpur,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,no,5,8
2,GP,F,15,Lalitpur,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,yes,5,8
3,GP,F,15,Lalitpur,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,yes,5,10
4,GP,F,16,Lalitpur,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,yes,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,Arunima School,M,20,Lalitpur,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,no,5,9
391,MS,M,17,Lalitpur,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,yes,5,7
392,MS,M,21,Kathmandu,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,no,5,8
393,MS,M,18,Kathmandu,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,yes,5,10
394,MS,M,19,Lalitpur,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,no,5,10

In [72]:
#Maximum and minimum value
df.groupby("address")["age"].min()

address
Kathmandu    15
Lalitpur     15
Name: age, dtype: int64

In [ ]:
df.groupby("address")["age"].max()

count students

In [73]:
df.groupby("sex").size()

sex
F    208
M    187
dtype: int64

***Assignments:***

show students with age above 20
find average age of each class